name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_DB: test_db
    #       POSTGRES_USER: test_user
    #       POSTGRES_PASSWORD: test_password
    #     ports:
    #       - "5432:5432"

    env:
      SECRET_KEY: "secret_key"
      DEBUG: False
      SENTRY_DSN: "https://your-sentry-dsn@sentry.io/your-project-id"
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: your-client-id.apps.googleusercontent.com
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: your-client-secret
      DB_NAME: testdb
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_PORT: 5432
      HOST_USER: admin
      HOST_PASSWORD: admin123
      HOST_EMAIL: admin@gmail.com
      SENTRY_ENABLED: False
      ENABLE_PROFILING: False

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-django coverage pytest-cov

      - name: Run tests with Coverage
        run: |
          source venv/bin/activate
          coverage run -m pytest --cov=. --cov-report=
          coverage report --fail-under=90

      - name: Generate Coverage Report (HTML)
        run: pytest --cov=. --cov-report=html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
